development:
  adapter: postgresql
  encoding: unicode
  database: testask_db
  pool: 5
  host: 'localhost'
  username: username
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  host: 'localhost'
  username: username
  password: password